module.exports = (app) => {
    const controller = require('../controllers/controller.js')

    app.get('/get_teams', controller.getteams)
    app.get('/get_users', controller.get_users)
    app.get('/get_ratings', controller.get_ratings)
    app.put('/update_rotation_details', controller.update_rotation_details)
    app.put('/update_event', controller.update_event)
    app.get('/get_user_events/:s', controller.get_user_events)
    app.get('/get_dates/:s', controller.get_dates)
    app.get('/get_user_feedback/:s', controller.get_user_feedback)
    app.get('/get_one_rating/:s', controller.get_one_rating)
    app.get('/get_one_rating2/:s', controller.get_one_rating2)
    app.get('/get_laters/:s', controller.get_laters)
    app.get('/get_my_feedback/:s', controller.get_my_feedback)
    app.get('/get_one_rating3/:s', controller.get_one_rating3)
    app.get('/get_name_and_surname/:s', controller.get_name_and_surname)
    app.get('/get_rotation_name/:s', controller.get_rotation_name)
    app.post('/insert_leave', controller.insert_leave)
    app.post('/insert_feedback', controller.insert_feedback)
    app.post('/send_feedback', controller.send_feedback)
    app.post('/insert_event', controller.insert_event)
    app.get('/search_teams/:s', controller.searchteams)
    app.get('/get_one_rotation/:s', controller.get_one_rotation)
    app.get('/search_users/:s', controller.search_users)
    app.get('/validation/:s', controller.validation)
    app.get('/validation2/:s', controller.validation2)
    app.get('/validation3/:s', controller.validation3)
    app.get('/get_events/:s', controller.get_events)
    app.get('/filter_events/:s', controller.filter_events)
    app.delete('/unsave_rotation/:i', controller.unsave_rotation)
}

